let data = JSON.parse(`{
    "ResultCode": "0000",
    "Status": "OK",
    "Data": {
      "Result": {
        "objOrderLog": [
          {
            "LogDateTime": "2019/05/28 13:23:33",
            "LogFunction": "EMAIL",
            "LogDesc2": "新光人壽網路投保-交易成功確認通知信：親愛的客戶您好，您已完成保單號碼：2026622301購買流程，本公司已收到您本人信用卡繳費NT$126請您放心！"
          }
        ],
        "objAccident": [
          {
            "number": 1,
            "policy_no": "2026622301",
            "plan_code": "20540",
            "plan_title": "新光人壽i-well傷害保險",
            "po_status_code": "4",
            "po_status_code_name": "正常繳費件",
            "po_issue_date": "2019/05/29 00:00:00",
            "po_issue_date_name": "民國108年5月29日午夜十二時起",
            "face_amt": 2000000,
            "expired_date": "2019/05/30 00:00:00",
            "expired_date_name": "民國108年5月30日午夜十二時止",
            "mode_prem": 80,
            "web_appl_ind": "3",
            "value_ind": null,
            "address3": "",
            "zip3": null,
            "city3": null,
            "district3": null,
            "road3": null,
            "email": null,
            "qpoop_25_prem": 126,
            "fst_anny_pay_age": null,
            "anny_frequence": null,
            "qpoop_19_year": null,
            "qpoop_25_modx": null,
            "modx_99_ind": null,
            "elec_rcpt_ind": null,
            "AccountData": [
              {
                "OrderNum": [
                  "account_type",
                  "bank_code_1",
                  "bank_code_2",
                  "account",
                  "naac_client_id"
                ],
                "account_type": "Z",
                "bank_code_1": null,
                "bank_name_1": "",
                "bank_code_2": null,
                "bank_name_2": "",
                "account": null,
                "naac_client_id": null,
                "UserNo": null
              }
            ],
            "account_type": null,
            "bank_code_1": null,
            "bank_name_1": null,
            "bank_code_2": null,
            "bank_name_2": null,
            "account": null,
            "AnnuityData": null,
            "method": null,
            "fullname": null,
            "account_bank": null,
            "card_type": null,
            "eff_date": null,
            "phone_area_o": null,
            "phone_number_o": null,
            "phone_remark_o": null,
            "phone_area_h": null,
            "phone_number_h": null,
            "phone_remark_h": null,
            "account_owner_ph_o": null,
            "account_owner_ph_h": null,
            "account_owner_ph_m": null,
            "rece_date": null,
            "currency_1": null,
            "CRSData": null
          },
          {
            "number": 2,
            "policy_no": "2026622301",
            "plan_code": "20551",
            "plan_title": "新光人壽網路投保傷害醫療保險附加條款",
            "po_status_code": "4",
            "po_status_code_name": "正常繳費件",
            "po_issue_date": "2019/05/29 00:00:00",
            "po_issue_date_name": "民國108年5月29日午夜十二時起",
            "face_amt": 20000,
            "expired_date": "2019/05/30 00:00:00",
            "expired_date_name": "民國108年5月30日午夜十二時止",
            "mode_prem": 46,
            "web_appl_ind": "3",
            "value_ind": null,
            "address3": "",
            "zip3": null,
            "city3": null,
            "district3": null,
            "road3": null,
            "email": null,
            "qpoop_25_prem": 126,
            "fst_anny_pay_age": null,
            "anny_frequence": null,
            "qpoop_19_year": null,
            "qpoop_25_modx": null,
            "modx_99_ind": null,
            "elec_rcpt_ind": null,
            "AccountData": [
              {
                "OrderNum": [
                  "account_type",
                  "bank_code_1",
                  "bank_code_2",
                  "account",
                  "naac_client_id"
                ],
                "account_type": "Z",
                "bank_code_1": null,
                "bank_name_1": "",
                "bank_code_2": null,
                "bank_name_2": "",
                "account": null,
                "naac_client_id": null,
                "UserNo": null
              }
            ],
            "account_type": null,
            "bank_code_1": null,
            "bank_name_1": null,
            "bank_code_2": null,
            "bank_name_2": null,
            "account": null,
            "AnnuityData": null,
            "method": null,
            "fullname": null,
            "account_bank": null,
            "card_type": null,
            "eff_date": null,
            "phone_area_o": null,
            "phone_number_o": null,
            "phone_remark_o": null,
            "phone_area_h": null,
            "phone_number_h": null,
            "phone_remark_h": null,
            "account_owner_ph_o": null,
            "account_owner_ph_h": null,
            "account_owner_ph_m": null,
            "rece_date": null,
            "currency_1": null,
            "CRSData": null
          }
        ],
        "IsSuccess": "1",
        "Msg": "",
        "OrderTime": "2019/05/28 13:23:26",
        "TN_ORDER_NO": "0200000000003853",
        "VerifyType": "OTP動態密碼驗證",
        "total_prem": "126",
        "pol_contract_typ": "E",
        "pol_contract_typ_name": "電子保單",
        "main_policy": "2026622301",
        "modx": "12",
        "modx_name": "年繳",
        "init_method": "C",
        "init_method_name": "信用卡",
        "PERIOD_NO": "",
        "client_name": "溜溜",
        "client_id": "O127309382",
        "client_rate_sex": "1",
        "client_rate_sex_name": "男",
        "client_birth": "1987/08/26 00:00:00",
        "client_birth_name": "民國76年08月26日，投保年齡為32歲",
        "benf_name": "法定繼承人",
        "relation_ben_death": "8",
        "relation_ben_death_name": "法定繼承人",
        "phoneH": "123-123",
        "phoneO": null,
        "MobilePhone": "0966789456",
        "address_M": "花蓮縣富里鄉1號",
        "address_1": "花蓮縣富里鄉1號",
        "address_notice": null,
        "client_marriage": "1",
        "client_marriage_name": "未婚",
        "insured_income": "500",
        "insured_fam_income": "800",
        "client_visit_time_ind": "010",
        "visit_time1": false,
        "visit_time2": true,
        "visit_time3": false,
        "client_rate_age": "32",
        "face_amt": 200,
        "occupation_class": "3",
        "occupation_class_code_name": "職別3（轉檔用）",
        "occupation_class_name": "第三類",
        "occupation_desc": "養殖、石化及放牧相關",
        "insured_peer_pla": null,
        "insured_peer_plan_1": "N",
        "BenfList": [
          {
            "benf_name": "法定繼承人",
            "relation_ben_death": "8",
            "relation_ben_death_name": "法定繼承人",
            "benf_id": null,
            "benf_phone": null,
            "percent1": "100",
            "percent2": "100",
            "prior_ben": "1",
            "address": null,
            "dob": null,
            "relation": "D",
            "nationality": null,
            "nationality_code": null
          }
        ],
        "client_height": null,
        "client_weight": null,
        "WEB_PAY_SOURCE": null,
        "BankTransferAgreementFile": null,
        "EMPLOYEE_NO": null,
        "EMPLOYEE_NAME": null,
        "QuestionAnswers": [
          "否",
          "否",
          "否",
          "否",
          "否"
        ],
        "method": null,
        "method_name": "",
        "nfo_name": "否",
        "fback_cash_opt": null,
        "fback_cash_opt_name": null,
        "fback_cash_opt_1": null,
        "fback_cash_opt_1_name": null,
        "IsDisplayPDFBtn": false,
        "Bank_name": null,
        "PreferredAccount": null,
        "RenewedPrefer": "BN",
        "RenewalPolicy": false,
        "revenue": 0,
        "price": 0
      },
      "IsSuccess": true,
      "Code": null,
      "Message": null,
      "Exceptions": null
    }
  }`)

export {
  data
}
