let data = JSON.parse(`{
    "ResultCode": "0000",
    "Status": "OK",
    "Data": {
        "Result": {
            "VerifyTypeList": {
                "3": "使用簡訊 OTP 動態密碼驗證，您的手機號碼為：0912345678"
            },
            "ID": "11843",
            "last_update_time": "2019/01/15 22:38:40",
            "step_status": "FILLIN",
            "InsAddressCity": "台北市",
            "InsAddressDistrict": "中正區",
            "InsAddressRoad": "死侍路1號1樓",
            "InsAddressZip": "100",
            "InsAddress": "台北市中正區死侍路1號1樓",
            "IsSuccess": true,
            "IsClose": false,
            "Msg": "",
            "ins_type": 4,
            "ins_type_name": "新光人壽My Way定期壽險",
            "po_issue_date": "2019/01/15 00:00:00",
            "po_issue_date_Name": "108年01月15日",
            "matured_date": "2020/01/15 00:00:00",
            "matured_date_Name": "109年01月15日",
            "client_rate_sex": "2",
            "client_birth": "1990/01/01 00:00:00",
            "Birthday_Full": "民國 79 年 01 月 01 日",
            "coverage_cnt": 1,
            "init_method": "C",
            "init_methodCht": "信用卡",
            "face_amt": 240,
            "face_amt_max": 300,
            "mode_prem": 1440,
            "Accept_ind": "",
            "plan_code": "LAA01",
            "version": "2",
            "client_occupation_class": "2",
            "client_occupation_class_name": "第二類",
            "client_occupation_class_detail": "外勤業務相關工作",
            "client_occupation_class_code": "18010090",
            "client_occupation_class_code_name": "警校教官",
            "client_id": "A222277777",
            "Nationality": "219",
            "client_names": "測試女",
            "web_appl_ind": "3",
            "Blacklist_ind": "N",
            "benf_num": "1",
            "relation_ben_death": "6",
            "benf_name": "死侍",
            "benf_dob": "1968/08/08 00:00:00",
            "benf_id": "X111111111",
            "benf_phone": "0222322232",
            "BenfAddZip": "208",
            "BenfAdd_City": "新北市",
            "BenfAdd_County": "金山區",
            "BenfAddRemain": "死侍路1號1樓",
            "BenfAddress": "新北市金山區死侍路1號1樓",
            "relation_ben_death_seq": "1",
            "relation_ben_death_seq_percent": "100",
            "BenfNationalityCode": "011",
            "BenfNationality": "阿魯巴",
            "BenfBankCode1": "103",
            "BenfBankBranch1": "0301",
            "BenfBankName1": "新光商銀",
            "BenfBankBranchName1": "新光銀建成",
            "BenfBankAccount1": "1021500062896",
            "relation_ben_death2": "",
            "benf_name2": "",
            "benf_dob2": null,
            "benf_id2": "",
            "benf_phone2": "",
            "BenfAddZip2": "",
            "BenfAdd_City2": "",
            "BenfAdd_County2": "",
            "BenfAddRemain2": "",
            "BenfAddress2": "",
            "relation_ben_death_seq2": "",
            "relation_ben_death_seq_percent2": "",
            "BenfNationalityCode2": null,
            "BenfNationality2": null,
            "BenfBankCode2": null,
            "BenfBankBranch2": null,
            "BenfBankName2": null,
            "BenfBankBranchName2": null,
            "BenfBankAccount2": null,
            "relation_ben_death3": "",
            "benf_name3": "",
            "benf_dob3": null,
            "benf_id3": "",
            "benf_phone3": "",
            "BenfAddZip3": "",
            "BenfAdd_City3": "",
            "BenfAdd_County3": "",
            "BenfAddRemain3": "",
            "BenfAddress3": "",
            "relation_ben_death_seq3": "",
            "relation_ben_death_seq_percent3": "",
            "BenfNationalityCode3": null,
            "BenfNationality3": null,
            "BenfBankCode3": null,
            "BenfBankBranch3": null,
            "BenfBankName3": null,
            "BenfBankBranchName3": null,
            "BenfBankAccount3": null,
            "adph_type": "3",
            "phone": "0912345678",
            "dicPhone": {
                "1": "02-8825252(52)",
                "3": "0912345678"
            },
            "phone_area": "02",
            "phone_main": "8825252",
            "phone_ext": "52",
            "phone_mobile": "0912345678",
            "address1Type": "1",
            "Agreement": null,
            "AgreementString": "新光人壽My Way定期壽險商品說明(21),新光人壽My Way定期壽險保險單條款(13),人壽保險投保人須知_網路投保(6),要保書填寫說明(2),蒐集、處理及利用個人資料告知事項(51),審閱期聲明書(3),病歷、醫療及健康檢查等個人資料蒐集、處理及利用聲明事項(3),電子單據服務約定事項(2)",
            "email": "skek1008@skl.com.tw",
            "zip1": "950",
            "address1": "台東縣臺東市臺東路1號1樓",
            "city1": "台東縣",
            "district1": "臺東市",
            "road1": "臺東路1號1樓",
            "IsSaveCommu": false,
            "address2Type": "0",
            "zip2": "965",
            "address2": "台東縣大武鄉死侍路1號1樓",
            "city2": "台東縣",
            "district2": "大武鄉",
            "road2": "死侍路1號1樓",
            "IsSaveRegistered": false,
            "owner_marriage": "1",
            "owner_marriage_name": "未婚",
            "insured_height": "180",
            "insured_weight": "60",
            "insured_income": "500",
            "insured_fam_income": "800",
            "visit_time_ind": "011",
            "visit_time1": "0",
            "visit_time2": "1",
            "visit_time3": "1",
            "pol_contract_typ": "P",
            "web_order_no": "",
            "Age": "29",
            "union_process_date": "2019/01/15",
            "union_batch_no": "154",
            "IsRetry": false,
            "QusAns": [
                {
                    "Answar": true,
                    "AnswarText": null
                },
                {
                    "Answar": true,
                    "AnswarText": null
                },
                {
                    "Answar": true,
                    "AnswarText": null
                },
                {
                    "Answar": true,
                    "AnswarText": null
                },
                {
                    "Answar": true,
                    "AnswarText": null
                },
                {
                    "Answar": true,
                    "AnswarText": null
                },
                {
                    "Answar": true,
                    "AnswarText": null
                },
                {
                    "Answar": true,
                    "AnswarText": null
                },
                {
                    "Answar": true,
                    "AnswarText": null
                }
            ],
            "DeclarationCode": [
                "R264",
                "R333"
            ],
            "address3Type": "0",
            "zip3": null,
            "address3": "",
            "city3": null,
            "district3": null,
            "road3": null,
            "qpoop_25_prem": 0,
            "fst_anny_pay_age": "",
            "anny_frequence": "",
            "qpoop_19_year": "",
            "qpoop_25_modx": "",
            "modx_99_ind": "",
            "value_ind": "",
            "elec_rcpt_ind": "",
            "AccountData": [
                {
                    "OrderNum": [
                        "account_type",
                        "bank_code_1",
                        "bank_code_2",
                        "account",
                        "naac_client_id"
                    ],
                    "account_type": "O",
                    "bank_code_1": "103",
                    "bank_name_1": "新光商銀",
                    "bank_code_2": "0310",
                    "bank_name_2": "新光銀北三重",
                    "account": "1021500062896",
                    "naac_client_id": "A222277777",
                    "UserNo": null
                },
                {
                    "OrderNum": [
                        "account_type",
                        "bank_code_1",
                        "bank_code_2",
                        "account",
                        "naac_client_id"
                    ],
                    "account_type": "D",
                    "bank_code_1": "103",
                    "bank_name_1": "新光商銀",
                    "bank_code_2": "0301",
                    "bank_name_2": "新光銀建成",
                    "account": "1021500062896",
                    "naac_client_id": "X111111111",
                    "UserNo": null
                }
            ],
            "account_type": null,
            "bank_code_1": null,
            "bank_name_1": null,
            "bank_code_2": null,
            "bank_name_2": null,
            "account": null,
            "Applicant_account_type": "O",
            "Applicant_BankCode": "103",
            "Applicant_BankName": "新光商銀",
            "Applicant_BranchCode": "0310",
            "Applicant_BranchName": "新光銀北三重",
            "Applicant_Account": "1021500062896",
            "AnnuityData": [],
            "method": "A",
            "methodCht": "銀行或郵局帳戶轉帳",
            "fullname": null,
            "account_bank": null,
            "card_type": null,
            "str_date": null,
            "eff_date": null,
            "rece_date": null,
            "currency_1": null,
            "fback_cash_opt": null,
            "fback_cash_opt_1": null,
            "modx": "12",
            "ProvisionReview": [
                {
                    "OrderNum": [
                        "check_yn",
                        "rule_get_date",
                        "rule_entry_date",
                        "plan_version"
                    ],
                    "check_yn": "Y",
                    "rule_get_date": "2019-01-11",
                    "rule_entry_date": "2019-01-15",
                    "plan_version": "LAA"
                }
            ],
            "insure_peer_pla": null,
            "insure_peer_plan_1": null,
            "web_collect_code": "",
            "web_equipment_code": "03",
            "original_policy_no": null,
            "accept_birthday_present": null,
            "EmployeeNo": null,
            "SalespersonName": null,
            "endterm_benf_relation": null,
            "endterm_benf_name": null,
            "endterm_benf_id": null,
            "endterm_benf_Phone": null,
            "endterm_benf_AddZip": "",
            "endterm_benf_Add_City": "",
            "endterm_benf_AddCounty": "",
            "endterm_benf_AddRemain": "",
            "endterm_benf_Address": "",
            "endterm_benf_dob": null,
            "endterm_benf_Nationality": null,
            "endterm_benf_NationalityCode": null,
            "USER_NO": null,
            "HavePreferredAccount": false,
            "Renewed_Prefer": false,
            "Payment_Prefer": false,
            "IsOneTimePayment": false,
            "OtpSendTime": null,
            "OtpValidateTime": null,
            "TrvDays": 0,
            "SupplementalTerms": null,
            "client_residency": "1",
            "Proposer": null,
            "rece_no": null,
            "AuthorizedRep": false,
            "SpouseAuthRep": null,
            "DependantAuthRep": null,
            "CRSData": {
                "OrderNum": [
                    "custname",
                    "custkey",
                    "crs_address_type",
                    "national_cd",
                    "other_address",
                    "birth",
                    "birth_city",
                    "birth_national_cd",
                    "sign_date",
                    "xcrsn_tax_type"
                ],
                "custname": null,
                "custkey": null,
                "crs_address_type": null,
                "national": null,
                "national_cd": null,
                "other_address": null,
                "birth": null,
                "birth_city": null,
                "birth_national": null,
                "birth_national_cd": null,
                "sign_date": null,
                "xcrsn_tax_type": null
            },
            "IsTaiwanTaxDuty": null,
            "OrderNo": null,
            "NoticeNo": null,
            "PayAMT": null,
            "PaymentStatus": null,
            "PolicyNo": null,
            "Year": 0,
            "Amount": 0
        },
        "IsSuccess": true,
        "Code": null,
        "Message": null,
        "Exceptions": null
    }
}`)

export {
  data
}
