export default {
  GetLoading: state => state.ShowLoading,
  GetJob: state => state.JOB,
  GetJobData: state => state.JOBDATA,
  GetCityData: state => state.CITYDATA,
  GetBank: state => state.BANK,
  GetBankData: state => state.BANKDATA,
  GetBankBranches: state => state.BANKBRANCHESDATA,
  GetNationData: state => state.NATIONDATA,
  GetOccupation: state => state.OCCUPATION,
  GetOccupationData: state => state.OCCUPATIONDATA,
  GetDistrictData: state => state.DISTRICTDATA,
  GetDistrictDataCommunity: state => state.DISTRICTDATACOMMUNITY,
  GetNotifyCheckBox: state => state.NOTIFYCHECKBOX,
  GetProvision: state => state.PROVISION,
  GetProvisionData: state => state.PROVISIONDATA,
  GetAccountData: state => state.ACCOUNTDATA,
  GetPremiums: state => state.PREMIUMS,
  GetJobSubCodeData: state => state.JOBSUBOCCUPATIONDATA,
  GetEachAccount: state => state.EACHACCOUNT
}
