import types from './types'
export default {
  GetLoading: state => state.ShowLoading,
  GetIsShowModal: state => state.isShowModal,
  [types.HeaderIsActive]: state => state.HeaderIsActive,
  [types.BenfinheritOneDisable]: state => state.BenfinheritOneDisable,
  GetJob: state => state.JOB,
  GetJobData: state => state.JOBDATA,
  GetCityData: state => state.CITYDATA,
  GetBank: state => state.BANK,
  GetBankData: state => state.BANKDATA,
  GetBankBranches: state => state.BANKBRANCHESDATA,
  GetBeneficiary: state => state.BENEFICIARY,
  GetNationData: state => state.NATIONDATA,
  GetOccupation: state => state.OCCUPATION,
  GetOccupationData: state => state.OCCUPATIONDATA,
  GetDistrictData: state => state.DISTRICTDATA,
  GetContactCheckBox: state => state.CONTACTCHECKBOX,
  GetNotifyCheckBox: state => state.NOTIFYCHECKBOX,
  GetProvision: state => state.PROVISION,
  GetAccountData: state => state.ACCOUNTDATA,
  GetPremiums: state => state.PREMIUMS,
  GetProvisionData: state => state.PROVISIONDATA,
  GetJobSubCodeData: state => state.JOBSUBOCCUPATIONDATA,
  GetPayCompleteData: state => state.PAYMENTCOMPLETE,
  GetEachAccount: state => state.EACHACCOUNT
}
