export default {
  ShowLoading: false,
  ApiToken: '',
  isShowModal: false,
  Http: {},
  HeaderIsActive: false,
  BenfinheritOneDisable: false,
  PLANNAME: '',
  ISCITYBANKCARD: false,
  CVV: '',
  CREDITCARD: '',
  PAYMENTCOMPLETE: [],
  JOB: '',
  JOBSUBCODE: '',
  JOBSUBOCCUPATIONDATA: '',
  JOBDATA: [],
  CITYDATA: [],
  EACHACCOUNT: [],
  BANK: [],
  BANKDATA: [],
  DISTRICTDATA: [],
  BANKBRANCHESDATA: [],
  BENEFICIARY: [],
  PROVISION: [],
  PROVISIONDATA: [],
  OTPSENDCODE: '',
  OTPVERIFY: '',
  OTPSENDTIME: '',
  OTPLASTTIME: '',
  NATION: '',
  NATIONDATA: [],
  OCCUPATION: '',
  OCCUPATIONDATA: [],
  CONTACTCHECKBOX: true,
  NOTIFYCHECKBOX: [
    true,
    false,
    false,
    false
  ]
}
