export default {
  MetuItem: 'MetuItem',
  MemberList: 'MemberList',
  AdminList: 'AdminList',
  GetMetuItem: 'GetMetuItem',
  GetMemberList: 'GetMemberList',
  GetMember: 'GetMember',
  GetAdminList: 'GetAdminList',
  GetAdmin: 'GetAdmin',
  GetVipList: 'GetVipList',
  AddVipList: 'AddVipList',
  AuthLogin: 'AuthLogin',
  AdminAddGet: 'AdminAddGet',
  AdminAddPost: 'AdminAddPost',
  AdminEditGet: 'AdminEditGet',
  AdminEditPut: 'AdminEditPut',
  AdminDel: 'AdminDel',
  AdminGroupList: 'AdminGroupList',
  GetAdminGroupList: 'GetAdminGroupList',
  GetAdminGroup: 'GetAdminGroup',
  GetShowLoading: 'GetShowLoading',
  ShowLoading: 'ShowLoading',
  HideLoading: 'HideLoading',
  ShowDiv: 'ShowDiv',
  HideDiv: 'HideDiv',
  GetAuth: 'GetAuth'
}
