let data = JSON.parse(`{
  "ResultCode": "0000",
  "Status": "OK",
  "Data": {
      "Result": {
          "VerifyTypeList": {
              "2": "使用簡訊 OTP 動態密碼驗證，您的手機號碼為：0987654321"
          },
          "ID": "11874",
          "last_update_time": "2019/01/17 17:48:45",
          "step_status": "FILLIN",
          "InsAddressCity": "基隆市",
          "InsAddressDistrict": "仁愛區",
          "InsAddressRoad": "123",
          "InsAddressZip": "200",
          "InsAddress": "基隆市仁愛區123",
          "IsSuccess": true,
          "IsClose": false,
          "Msg": "",
          "ins_type": 5,
          "ins_type_name": "新光人壽New Health健康保險",
          "po_issue_date": "2019/01/17 00:00:00",
          "po_issue_date_Name": "108年01月17日",
          "matured_date": "2020/01/17 00:00:00",
          "matured_date_Name": "109年01月17日",
          "client_rate_sex": "2",
          "client_birth": "1997/06/10 00:00:00",
          "Birthday_Full": "民國 86 年 06 月 10 日",
          "coverage_cnt": 1,
          "init_method": "C",
          "init_methodCht": "信用卡",
          "face_amt": 3,
          "face_amt_max": 600,
          "mode_prem": 1673,
          "Accept_ind": "",
          "plan_code": "KAA01",
          "version": "1",
          "client_occupation_class": "2",
          "client_occupation_class_name": "第二類",
          "client_occupation_class_detail": "外勤業務相關工作",
          "client_occupation_class_code": "18010090",
          "client_occupation_class_code_name": "警校教官",
          "client_id": "A234485716",
          "Nationality": "219",
          "client_names": "嗨",
          "web_appl_ind": "2",
          "Blacklist_ind": "N",
          "benf_num": "2",
          "relation_ben_death": "6",
          "benf_name": "死侍",
          "benf_dob": "1988/08/08 00:00:00",
          "benf_id": "X111111111",
          "benf_phone": "0912345678",
          "BenfAddZip": "208",
          "BenfAdd_City": "新北市",
          "BenfAdd_County": "金山區",
          "BenfAddRemain": "回頭問問1號",
          "BenfAddress": "新北市金山區回頭問問1號",
          "relation_ben_death_seq": "1",
          "relation_ben_death_seq_percent": "100",
          "BenfNationalityCode": null,
          "BenfNationality": "阿魯巴",
          "BenfBankCode1": null,
          "BenfBankBranch1": null,
          "BenfBankName1": null,
          "BenfBankBranchName1": null,
          "BenfBankAccount1": null,
          "relation_ben_death2": "3",
          "benf_name2": "鋼鐵人",
          "benf_dob2": "1988/09/09 00:00:00",
          "benf_id2": "A222277777",
          "benf_phone2": "0931123321",
          "BenfAddZip2": "103",
          "BenfAdd_City2": "台北市",
          "BenfAdd_County2": "大同區",
          "BenfAddRemain2": "圍觀看了1號",
          "BenfAddress2": "台北市大同區圍觀看了1號",
          "relation_ben_death_seq2": "2",
          "relation_ben_death_seq_percent2": "100",
          "BenfNationalityCode2": null,
          "BenfNationality2": "阿魯巴",
          "BenfBankCode2": null,
          "BenfBankBranch2": null,
          "BenfBankName2": null,
          "BenfBankBranchName2": null,
          "BenfBankAccount2": null,
          "relation_ben_death3": "",
          "benf_name3": "",
          "benf_dob3": null,
          "benf_id3": "",
          "benf_phone3": "",
          "BenfAddZip3": "",
          "BenfAdd_City3": "",
          "BenfAdd_County3": "",
          "BenfAddRemain3": "",
          "BenfAddress3": "",
          "relation_ben_death_seq3": null,
          "relation_ben_death_seq_percent3": null,
          "BenfNationalityCode3": null,
          "BenfNationality3": null,
          "BenfBankCode3": null,
          "BenfBankBranch3": null,
          "BenfBankName3": null,
          "BenfBankBranchName3": null,
          "BenfBankAccount3": null,
          "adph_type": "3",
          "phone": "0987654321",
          "dicPhone": {
              "1": "02-8825252(52)",
              "3": "0987654321"
          },
          "phone_area": "02",
          "phone_main": "8825252",
          "phone_ext": "52",
          "phone_mobile": "0987654321",
          "address1Type": "1",
          "Agreement": null,
          "AgreementString": "新光人壽New Health健康保險商品說明(12),新光人壽New Health健康保險保險單條款(5),人壽保險投保人須知_網路投保(6),要保書填寫說明(2),蒐集、處理及利用個人資料告知事項(51),病歷、醫療及健康檢查等個人資料蒐集、處理及利用聲明事項(3),電子單據服務約定事項(2)",
          "email": "skem2530@skl.com.tw",
          "zip1": "950",
          "address1": "台北市中正區台北市路1號1樓",
          "city1": "台北市",
          "district1": "中正區",
          "road1": "台北市路1號1樓",
          "IsSaveCommu": false,
          "address2Type": "1",
          "zip2": "983",
          "address2": "台東縣大武鄉死侍路1號1樓",
          "city2": "台東縣",
          "district2": "大武鄉",
          "road2": "死侍路1號1樓",
          "IsSaveRegistered": false,
          "owner_marriage": "1",
          "owner_marriage_name": "未婚",
          "insured_height": "180",
          "insured_weight": "60",
          "insured_income": "500",
          "insured_fam_income": "800",
          "visit_time_ind": "101",
          "visit_time1": "1",
          "visit_time2": "0",
          "visit_time3": "1",
          "pol_contract_typ": "P",
          "web_order_no": "",
          "Age": "22",
          "union_process_date": "2019/01/17",
          "union_batch_no": "28",
          "IsRetry": false,
          "QusAns": [
              {
                  "Answar": true,
                  "AnswarText": null
              },
              {
                  "Answar": true,
                  "AnswarText": null
              },
              {
                  "Answar": true,
                  "AnswarText": null
              },
              {
                  "Answar": true,
                  "AnswarText": null
              },
              {
                  "Answar": true,
                  "AnswarText": null
              },
              {
                  "Answar": true,
                  "AnswarText": null
              },
              {
                  "Answar": true,
                  "AnswarText": null
              },
              {
                  "Answar": true,
                  "AnswarText": null
              },
              {
                  "Answar": true,
                  "AnswarText": null
              },
              {
                  "Answar": true,
                  "AnswarText": null
              },
              {
                  "Answar": true,
                  "AnswarText": null
              }
          ],
          "DeclarationCode": [
              "R333"
          ],
          "address3Type": "0",
          "zip3": null,
          "address3": "",
          "city3": null,
          "district3": null,
          "road3": null,
          "qpoop_25_prem": 0,
          "fst_anny_pay_age": "",
          "anny_frequence": "",
          "qpoop_19_year": "",
          "qpoop_25_modx": "",
          "modx_99_ind": "",
          "value_ind": "",
          "elec_rcpt_ind": "",
          "AccountData": [
              {
                  "OrderNum": [
                      "account_type",
                      "bank_code_1",
                      "bank_code_2",
                      "account",
                      "naac_client_id"
                  ],
                  "account_type": "O",
                  "bank_code_1": "103",
                  "bank_name_1": "新光商銀",
                  "bank_code_2": "0310",
                  "bank_name_2": "新光銀北三重",
                  "account": "1021500062896",
                  "naac_client_id": "A234485716",
                  "UserNo": null
              }
          ],
          "account_type": null,
          "bank_code_1": null,
          "bank_name_1": null,
          "bank_code_2": null,
          "bank_name_2": null,
          "account": null,
          "Applicant_account_type": "O",
          "Applicant_BankCode": "103",
          "Applicant_BankName": "新光商銀",
          "Applicant_BranchCode": "0310",
          "Applicant_BranchName": "新光銀北三重",
          "Applicant_Account": "1021500062896",
          "AnnuityData": [],
          "method": "A",
          "methodCht": "銀行或郵局帳戶轉帳",
          "fullname": null,
          "account_bank": null,
          "card_type": null,
          "str_date": null,
          "eff_date": null,
          "rece_date": null,
          "currency_1": null,
          "fback_cash_opt": null,
          "fback_cash_opt_1": null,
          "modx": "12",
          "ProvisionReview": [],
          "insure_peer_pla": "N",
          "insure_peer_plan_1": null,
          "web_collect_code": "",
          "web_equipment_code": "03",
          "original_policy_no": null,
          "accept_birthday_present": null,
          "EmployeeNo": null,
          "SalespersonName": null,
          "endterm_benf_relation": null,
          "endterm_benf_name": null,
          "endterm_benf_id": null,
          "endterm_benf_Phone": null,
          "endterm_benf_AddZip": "",
          "endterm_benf_Add_City": "",
          "endterm_benf_AddCounty": "",
          "endterm_benf_AddRemain": "",
          "endterm_benf_Address": "",
          "endterm_benf_dob": null,
          "endterm_benf_Nationality": null,
          "endterm_benf_NationalityCode": null,
          "USER_NO": null,
          "HavePreferredAccount": false,
          "Renewed_Prefer": false,
          "Payment_Prefer": false,
          "IsOneTimePayment": false,
          "OtpSendTime": null,
          "OtpValidateTime": null,
          "TrvDays": 0,
          "SupplementalTerms": null,
          "client_residency": "1",
          "Proposer": null,
          "rece_no": null,
          "AuthorizedRep": false,
          "SpouseAuthRep": null,
          "DependantAuthRep": null,
          "CRSData": {
              "OrderNum": [
                  "custname",
                  "custkey",
                  "crs_address_type",
                  "national_cd",
                  "other_address",
                  "birth",
                  "birth_city",
                  "birth_national_cd",
                  "sign_date",
                  "xcrsn_tax_type"
              ],
              "custname": null,
              "custkey": null,
              "crs_address_type": null,
              "national": null,
              "national_cd": null,
              "other_address": null,
              "birth": null,
              "birth_city": null,
              "birth_national": null,
              "birth_national_cd": null,
              "sign_date": null,
              "xcrsn_tax_type": null
          },
          "IsTaiwanTaxDuty": null,
          "OrderNo": null,
          "NoticeNo": null,
          "PayAMT": null,
          "PaymentStatus": null,
          "PolicyNo": null,
          "Year": 0,
          "Amount": 0
      },
      "IsSuccess": true,
      "Code": null,
      "Message": null,
      "Exceptions": null
  }
}`)

export {
  data
}
