let data = JSON.parse(`{
    "ResultCode": "0000",
    "Status": "OK",
    "Data": {
        "Result": {
            "VerifyTypeList": {
                "3": "使用簡訊 OTP 動態密碼驗證，您的手機號碼為：0952184733"
            },
            "ID": "11870",
            "last_update_time": "2019/01/16 17:48:43",
            "step_status": "FILLIN",
            "InsAddressCity": "新北市",
            "InsAddressDistrict": "樹林區",
            "InsAddressRoad": "樹林路2號",
            "InsAddressZip": "238",
            "InsAddress": "新北市樹林區樹林路2號",
            "IsSuccess": true,
            "IsClose": false,
            "Msg": "",
            "ins_type": 2,
            "ins_type_name": "新光人壽i平安傷害保險",
            "po_issue_date": "2019/01/16 00:00:00",
            "po_issue_date_Name": "108年01月16日",
            "matured_date": "2020/01/16 00:00:00",
            "matured_date_Name": "109年01月16日",
            "client_rate_sex": "2",
            "client_birth": "1986/07/15 00:00:00",
            "Birthday_Full": "民國 75 年 07 月 15 日",
            "coverage_cnt": 1,
            "init_method": "C",
            "init_methodCht": "信用卡",
            "face_amt": 90,
            "face_amt_max": 300,
            "mode_prem": 846,
            "Accept_ind": "",
            "plan_code": "20511",
            "version": "5",
            "client_occupation_class": "2",
            "client_occupation_class_name": "第二類",
            "client_occupation_class_detail": "外勤業務相關工作",
            "client_occupation_class_code": null,
            "client_occupation_class_code_name": null,
            "client_id": "F261000108",
            "Nationality": "219",
            "client_names": "請輸入",
            "web_appl_ind": "3",
            "Blacklist_ind": "N",
            "benf_num": "3",
            "relation_ben_death": "6",
            "benf_name": "死侍",
            "benf_dob": "1988/08/08 00:00:00",
            "benf_id": "X111111111",
            "benf_phone": "0912345678",
            "BenfAddZip": "208",
            "BenfAdd_City": "新北市",
            "BenfAdd_County": "金山區",
            "BenfAddRemain": "回頭問問1號",
            "BenfAddress": "新北市金山區回頭問問1號",
            "relation_ben_death_seq": "1",
            "relation_ben_death_seq_percent": "100",
            "BenfNationalityCode": "011",
            "BenfNationality": "阿魯巴",
            "BenfBankCode1": null,
            "BenfBankBranch1": null,
            "BenfBankName1": null,
            "BenfBankBranchName1": null,
            "BenfBankAccount1": null,
            "relation_ben_death2": "3",
            "benf_name2": "鋼鐵人",
            "benf_dob2": "1988/09/09 00:00:00",
            "benf_id2": "A222277777",
            "benf_phone2": "0931123321",
            "BenfAddZip2": "103",
            "BenfAdd_City2": "台北市",
            "BenfAdd_County2": "大同區",
            "BenfAddRemain2": "圍觀看了1號",
            "BenfAddress2": "台北市大同區圍觀看了1號",
            "relation_ben_death_seq2": "2",
            "relation_ben_death_seq_percent2": "100",
            "BenfNationalityCode2": "011",
            "BenfNationality2": "阿魯巴",
            "BenfBankCode2": null,
            "BenfBankBranch2": null,
            "BenfBankName2": null,
            "BenfBankBranchName2": null,
            "BenfBankAccount2": null,
            "relation_ben_death3": "2",
            "benf_name3": "金鋼狼",
            "benf_dob3": "1988/03/03 00:00:00",
            "benf_id3": "Z175429240",
            "benf_phone3": "0934514415",
            "BenfAddZip3": "103",
            "BenfAdd_City3": "台北市",
            "BenfAdd_County3": "大同區",
            "BenfAddRemain3": "離開金額我1號",
            "BenfAddress3": "台北市大同區離開金額我1號",
            "relation_ben_death_seq3": "3",
            "relation_ben_death_seq_percent3": "100",
            "BenfNationalityCode3": "011",
            "BenfNationality3": "阿魯巴",
            "BenfBankCode3": null,
            "BenfBankBranch3": null,
            "BenfBankName3": null,
            "BenfBankBranchName3": null,
            "BenfBankAccount3": null,
            "adph_type": "3",
            "phone": "0952184733",
            "dicPhone": {
                "1": "02-8825252(52)",
                "3": "0952184733"
            },
            "phone_area": "02",
            "phone_main": "8825252",
            "phone_ext": "52",
            "phone_mobile": "0952184733",
            "address1Type": "1",
            "Agreement": null,
            "AgreementString": "新光人壽i平安傷害保險商品說明(1),新光人壽i平安傷害保險保險單條款(15),新光人壽網路投保個人傷害險投保人須知(7),新光人壽網路投保個人傷害保險要保書填寫說明(3),蒐集、處理及利用個人資料告知事項(51),病歷、醫療及健康檢查等個人資料蒐集、處理及利用聲明事項(3),電子單據服務約定事項(2)",
            "email": "skek1008@skl.com.tw",
            "zip1": "950",
            "address1": "台北市中正區台北市路1號1樓",
            "city1": "台北市",
            "district1": "中正區",
            "road1": "台北市路1號1樓",
            "IsSaveCommu": false,
            "address2Type": "1",
            "zip2": "983",
            "address2": "台東縣大武鄉死侍路1號1樓",
            "city2": "台東縣",
            "district2": "大武鄉",
            "road2": "死侍路1號1樓",
            "IsSaveRegistered": false,
            "owner_marriage": "2",
            "owner_marriage_name": "已婚",
            "insured_height": null,
            "insured_weight": null,
            "insured_income": "500",
            "insured_fam_income": "800",
            "visit_time_ind": "011",
            "visit_time1": "0",
            "visit_time2": "1",
            "visit_time3": "1",
            "pol_contract_typ": "P",
            "web_order_no": "",
            "Age": "33",
            "union_process_date": "2019/01/16",
            "union_batch_no": "126",
            "IsRetry": false,
            "QusAns": [
                {
                    "Answar": true,
                    "AnswarText": null
                },
                {
                    "Answar": true,
                    "AnswarText": null
                },
                {
                    "Answar": true,
                    "AnswarText": null
                },
                {
                    "Answar": true,
                    "AnswarText": null
                }
            ],
            "DeclarationCode": [
                "R333"
            ],
            "address3Type": "0",
            "zip3": null,
            "address3": "",
            "city3": null,
            "district3": null,
            "road3": null,
            "qpoop_25_prem": 0,
            "fst_anny_pay_age": "",
            "anny_frequence": "",
            "qpoop_19_year": "",
            "qpoop_25_modx": "",
            "modx_99_ind": "",
            "value_ind": "",
            "elec_rcpt_ind": "",
            "AccountData": [],
            "account_type": null,
            "bank_code_1": null,
            "bank_name_1": null,
            "bank_code_2": null,
            "bank_name_2": null,
            "account": null,
            "Applicant_account_type": "O",
            "Applicant_BankCode": null,
            "Applicant_BankName": null,
            "Applicant_BranchCode": null,
            "Applicant_BranchName": null,
            "Applicant_Account": null,
            "AnnuityData": [],
            "method": "A",
            "methodCht": "銀行或郵局帳戶轉帳",
            "fullname": null,
            "account_bank": null,
            "card_type": null,
            "str_date": null,
            "eff_date": null,
            "rece_date": null,
            "currency_1": null,
            "fback_cash_opt": null,
            "fback_cash_opt_1": null,
            "modx": "12",
            "ProvisionReview": [],
            "insure_peer_pla": null,
            "insure_peer_plan_1": null,
            "web_collect_code": "",
            "web_equipment_code": "03",
            "original_policy_no": null,
            "accept_birthday_present": null,
            "EmployeeNo": null,
            "SalespersonName": null,
            "endterm_benf_relation": null,
            "endterm_benf_name": null,
            "endterm_benf_id": null,
            "endterm_benf_Phone": null,
            "endterm_benf_AddZip": "",
            "endterm_benf_Add_City": "",
            "endterm_benf_AddCounty": "",
            "endterm_benf_AddRemain": "",
            "endterm_benf_Address": "",
            "endterm_benf_dob": null,
            "endterm_benf_Nationality": null,
            "endterm_benf_NationalityCode": null,
            "USER_NO": null,
            "HavePreferredAccount": false,
            "Renewed_Prefer": false,
            "Payment_Prefer": false,
            "IsOneTimePayment": false,
            "OtpSendTime": null,
            "OtpValidateTime": null,
            "TrvDays": 0,
            "SupplementalTerms": null,
            "client_residency": "1",
            "Proposer": null,
            "rece_no": null,
            "AuthorizedRep": false,
            "SpouseAuthRep": null,
            "DependantAuthRep": null,
            "CRSData": {
                "OrderNum": [
                    "custname",
                    "custkey",
                    "crs_address_type",
                    "national_cd",
                    "other_address",
                    "birth",
                    "birth_city",
                    "birth_national_cd",
                    "sign_date",
                    "xcrsn_tax_type"
                ],
                "custname": null,
                "custkey": null,
                "crs_address_type": null,
                "national": null,
                "national_cd": null,
                "other_address": null,
                "birth": null,
                "birth_city": null,
                "birth_national": null,
                "birth_national_cd": null,
                "sign_date": null,
                "xcrsn_tax_type": null
            },
            "IsTaiwanTaxDuty": null,
            "OrderNo": null,
            "NoticeNo": null,
            "PayAMT": null,
            "PaymentStatus": null,
            "PolicyNo": null,
            "Year": 0,
            "Amount": 0
        },
        "IsSuccess": true,
        "Code": null,
        "Message": null,
        "Exceptions": null
    }
}`)

export {
  data
}
