let data = JSON.parse(`{
  "ResultCode": "0000",
  "Status": "OK",
  "Data": {
      "Result": {
          "VerifyTypeList": {
              "3": "使用簡訊 OTP 動態密碼驗證，您的手機號碼為：0975620509"
          },
          "ID": "11797",
          "last_update_time": "2019/01/08 11:35:09",
          "step_status": "FILLIN",
          "InsAddressCity": "台東縣",
          "InsAddressDistrict": "臺東市",
          "InsAddressRoad": "臺東路1號1樓",
          "InsAddressZip": "950",
          "InsAddress": "台東縣臺東市臺東路1號1樓",
          "IsSuccess": true,
          "IsClose": false,
          "Msg": "",
          "ins_type": 6,
          "ins_type_name": "新光人壽 Up Cash 利率變動型年金保險【乙型】",
          "po_issue_date": "2019/01/08 00:00:00",
          "po_issue_date_Name": "108年01月08日",
          "matured_date": "2020/01/08 00:00:00",
          "matured_date_Name": "109年01月08日",
          "client_rate_sex": "2",
          "client_birth": "1990/01/01 00:00:00",
          "Birthday_Full": "民國 79 年 01 月 01 日",
          "coverage_cnt": 1,
          "init_method": "C",
          "init_methodCht": "信用卡",
          "face_amt": 666666,
          "face_amt_max": 0,
          "mode_prem": 666666,
          "Accept_ind": "",
          "plan_code": "UC099",
          "version": "1",
          "client_occupation_class": "4",
          "client_occupation_class_name": "第四類",
          "client_occupation_class_detail": "司機、採石及水電修理相關",
          "client_occupation_class_code": "16030280",
          "client_occupation_class_code_name": "搬家工人",
          "client_id": "A222277777",
          "Nationality": "219",
          "client_names": "測試女",
          "web_appl_ind": "3",
          "Blacklist_ind": "N",
          "benf_num": "1",
          "relation_ben_death": "6",
          "benf_name": "死侍",
          "benf_dob": "1968/08/08 00:00:00",
          "benf_id": "X111111111",
          "benf_phone": "0222322232",
          "BenfAddZip": "208",
          "BenfAdd_City": "新北市",
          "BenfAdd_County": "金山區",
          "BenfAddRemain": "死侍路1號1樓",
          "BenfAddress": "新北市金山區死侍路1號1樓",
          "relation_ben_death_seq": "1",
          "relation_ben_death_seq_percent": "100",
          "BenfNationalityCode": "011",
          "BenfNationality": "阿魯巴",
          "BenfBankCode1": "103",
          "BenfBankBranch1": "0301",
          "BenfBankName1": "新光商銀",
          "BenfBankBranchName1": "新光銀建成",
          "BenfBankAccount1": "1021500062896",
          "relation_ben_death2": "",
          "benf_name2": "",
          "benf_dob2": null,
          "benf_id2": "",
          "benf_phone2": "",
          "BenfAddZip2": "",
          "BenfAdd_City2": "",
          "BenfAdd_County2": "",
          "BenfAddRemain2": "",
          "BenfAddress2": "",
          "relation_ben_death_seq2": "",
          "relation_ben_death_seq_percent2": "",
          "BenfNationalityCode2": "",
          "BenfNationality2": "",
          "BenfBankCode2": null,
          "BenfBankBranch2": null,
          "BenfBankName2": null,
          "BenfBankBranchName2": null,
          "BenfBankAccount2": null,
          "relation_ben_death3": "",
          "benf_name3": "",
          "benf_dob3": null,
          "benf_id3": "",
          "benf_phone3": "",
          "BenfAddZip3": "",
          "BenfAdd_City3": "",
          "BenfAdd_County3": "",
          "BenfAddRemain3": "",
          "BenfAddress3": "",
          "relation_ben_death_seq3": "",
          "relation_ben_death_seq_percent3": "",
          "BenfNationalityCode3": "",
          "BenfNationality3": "",
          "BenfBankCode3": null,
          "BenfBankBranch3": null,
          "BenfBankName3": null,
          "BenfBankBranchName3": null,
          "BenfBankAccount3": null,
          "adph_type": "3",
          "phone": "0975620509",
          "dicPhone": {
              "1": "02-8825252(52)",
              "3": "0975620509"
          },
          "phone_area": "02",
          "phone_main": "8825252",
          "phone_ext": "52",
          "phone_mobile": "0975620509",
          "address1Type": "0",
          "Agreement": null,
          "AgreementString": null,
          "email": "skek1008@skl.com.tw",
          "zip1": "950",
          "address1": "台東縣臺東市臺東路1號1樓",
          "city1": "台東縣",
          "district1": "臺東市",
          "road1": "臺東路1號1樓",
          "IsSaveCommu": true,
          "address2Type": "0",
          "zip2": "983",
          "address2": "花蓮縣富里鄉富里路1號",
          "city2": "花蓮縣",
          "district2": "富里鄉",
          "road2": "富里路1號",
          "IsSaveRegistered": true,
          "owner_marriage": "1",
          "owner_marriage_name": "未婚",
          "insured_height": null,
          "insured_weight": null,
          "insured_income": "500",
          "insured_fam_income": "800",
          "visit_time_ind": "011",
          "visit_time1": "0",
          "visit_time2": "1",
          "visit_time3": "1",
          "pol_contract_typ": "P",
          "web_order_no": "",
          "Age": "29",
          "union_process_date": "2019/01/08",
          "union_batch_no": "47",
          "IsRetry": false,
          "QusAns": null,
          "DeclarationCode": [
              "R353",
              "R333"
          ],
          "address3Type": "0",
          "zip3": "950",
          "address3": "台東縣臺東市臺東路1號1樓",
          "city3": "台東縣",
          "district3": "臺東市",
          "road3": "臺東路1號1樓",
          "qpoop_25_prem": null,
          "fst_anny_pay_age": "35",
          "anny_frequence": "0",
          "qpoop_19_year": "",
          "qpoop_25_modx": "",
          "modx_99_ind": "",
          "value_ind": "4",
          "elec_rcpt_ind": "Y",
          "AccountData": [
              {
                  "OrderNum": [
                      "account_type",
                      "bank_code_1",
                      "bank_code_2",
                      "account",
                      "naac_client_id"
                  ],
                  "account_type": "O",
                  "bank_code_1": "103",
                  "bank_name_1": "新光商銀",
                  "bank_code_2": "0310",
                  "bank_name_2": "新光銀北三重",
                  "account": "1021500062896",
                  "naac_client_id": "A222277777",
                  "UserNo": null
              },
              {
                  "OrderNum": [
                      "account_type",
                      "bank_code_1",
                      "bank_code_2",
                      "account",
                      "naac_client_id"
                  ],
                  "account_type": "I",
                  "bank_code_1": "103",
                  "bank_name_1": "新光商銀",
                  "bank_code_2": "0310",
                  "bank_name_2": "新光銀北三重",
                  "account": "1021500062896",
                  "naac_client_id": "A222277777",
                  "UserNo": null
              },
              {
                  "OrderNum": [
                      "account_type",
                      "bank_code_1",
                      "bank_code_2",
                      "account",
                      "naac_client_id"
                  ],
                  "account_type": "D",
                  "bank_code_1": "103",
                  "bank_name_1": "新光商銀",
                  "bank_code_2": "0301",
                  "bank_name_2": "新光銀建成",
                  "account": "1021500062896",
                  "naac_client_id": "X111111111",
                  "UserNo": null
              }
          ],
          "account_type": "I",
          "bank_code_1": null,
          "bank_name_1": null,
          "bank_code_2": null,
          "bank_name_2": null,
          "account": null,
          "Applicant_account_type": "O",
          "Applicant_BankCode": "103",
          "Applicant_BankName": "新光商銀",
          "Applicant_BranchCode": "0310",
          "Applicant_BranchName": "新光銀北三重",
          "Applicant_Account": "1021500062896",
          "AnnuityData": [],
          "method": "P",
          "methodCht": "銀行或郵局帳戶轉帳",
          "fullname": null,
          "account_bank": null,
          "card_type": null,
          "str_date": null,
          "eff_date": null,
          "rece_date": null,
          "currency_1": "NTD",
          "fback_cash_opt": null,
          "fback_cash_opt_1": null,
          "modx": "0",
          "ProvisionReview": [],
          "insure_peer_pla": null,
          "insure_peer_plan_1": null,
          "web_collect_code": "",
          "web_equipment_code": "03",
          "original_policy_no": null,
          "accept_birthday_present": null,
          "EmployeeNo": null,
          "SalespersonName": null,
          "endterm_benf_relation": null,
          "endterm_benf_name": null,
          "endterm_benf_id": null,
          "endterm_benf_Phone": null,
          "endterm_benf_AddZip": "",
          "endterm_benf_Add_City": "",
          "endterm_benf_AddCounty": "",
          "endterm_benf_AddRemain": "",
          "endterm_benf_Address": "",
          "endterm_benf_dob": null,
          "endterm_benf_Nationality": null,
          "endterm_benf_NationalityCode": null,
          "USER_NO": "",
          "HavePreferredAccount": false,
          "Renewed_Prefer": false,
          "Payment_Prefer": false,
          "IsOneTimePayment": true,
          "OtpSendTime": null,
          "OtpValidateTime": null,
          "TrvDays": 0,
          "SupplementalTerms": null,
          "client_residency": "1",
          "Proposer": null,
          "rece_no": null,
          "AuthorizedRep": null,
          "SpouseAuthRep": null,
          "DependantAuthRep": null,
          "CRSData": {
              "OrderNum": [
                  "custname",
                  "custkey",
                  "crs_address_type",
                  "national_cd",
                  "other_address",
                  "birth",
                  "birth_city",
                  "birth_national_cd",
                  "sign_date",
                  "xcrsn_tax_type"
              ],
              "custname": null,
              "custkey": null,
              "crs_address_type": "1",
              "national": null,
              "national_cd": null,
              "other_address": null,
              "birth": null,
              "birth_city": "城市",
              "birth_national": "阿魯巴",
              "birth_national_cd": "011",
              "sign_date": null,
              "xcrsn_tax_type": "1"
          },
          "IsTaiwanTaxDuty": true,
          "OrderNo": null,
          "NoticeNo": null,
          "PayAMT": null,
          "PaymentStatus": null,
          "PolicyNo": null,
          "Year": 0,
          "Amount": 0
      },
      "IsSuccess": true,
      "Code": null,
      "Message": null,
      "Exceptions": null
  }
}`)

export {
  data
}
