let data = JSON.parse(`
    {
        "ResultCode": "0000",
        "Status": "OK",
        "Data": {
          "Result": {
            "objOrderLog": [
              {
                "LogDateTime": "2019/05/28 00:36:30",
                "LogFunction": "EMAIL",
                "LogDesc2": "新光人壽網路投保-交易成功確認通知信：親愛的客戶您好，您已完成保單號碼：9006353133購買流程，本公司已收到您本人信用卡繳費NT$33333請您放心！"
              }
            ],
            "objAccident": [
              {
                "number": 1,
                "policy_no": "9006353133",
                "plan_code": "UCA99",
                "plan_title": "新光人壽Up Cash利率變動型年金保險【乙型】",
                "po_status_code": "4",
                "po_status_code_name": "正常繳費件",
                "po_issue_date": "2019/05/28 00:00:00",
                "po_issue_date_name": "民國108年5月28日午夜十二時起",
                "face_amt": 0,
                "expired_date": "2101/05/28 00:00:00",
                "expired_date_name": "民國190年5月28日午夜十二時止",
                "mode_prem": 33333,
                "web_appl_ind": "3",
                "value_ind": "4",
                "address3": "台東縣臺東市臺東路1號1樓",
                "zip3": "",
                "city3": "",
                "district3": "",
                "road3": "台東縣臺東市臺東路1號1樓",
                "email": null,
                "qpoop_25_prem": 3333,
                "fst_anny_pay_age": "34",
                "anny_frequence": "3",
                "qpoop_19_year": "15",
                "qpoop_25_modx": "12",
                "modx_99_ind": "N",
                "elec_rcpt_ind": null,
                "AccountData": [
                  {
                    "OrderNum": [
                      "account_type",
                      "bank_code_1",
                      "bank_code_2",
                      "account",
                      "naac_client_id"
                    ],
                    "account_type": "I",
                    "bank_code_1": "",
                    "bank_name_1": "新光商銀",
                    "bank_code_2": "",
                    "bank_name_2": "新光銀基隆",
                    "account": "1021500062896",
                    "naac_client_id": null,
                    "UserNo": null
                  },
                  {
                    "OrderNum": [
                      "account_type",
                      "bank_code_1",
                      "bank_code_2",
                      "account",
                      "naac_client_id"
                    ],
                    "account_type": "Z",
                    "bank_code_1": null,
                    "bank_name_1": "",
                    "bank_code_2": null,
                    "bank_name_2": "",
                    "account": null,
                    "naac_client_id": null,
                    "UserNo": null
                  },
                  {
                    "OrderNum": [
                      "account_type",
                      "bank_code_1",
                      "bank_code_2",
                      "account",
                      "naac_client_id"
                    ],
                    "account_type": "D",
                    "bank_code_1": "103",
                    "bank_name_1": "新光商銀",
                    "bank_code_2": "0718",
                    "bank_name_2": "新光銀宜蘭",
                    "account": "1021500062896",
                    "naac_client_id": "x111111111",
                    "UserNo": null
                  },
                  {
                    "OrderNum": [
                      "account_type",
                      "bank_code_1",
                      "bank_code_2",
                      "account",
                      "naac_client_id"
                    ],
                    "account_type": "D",
                    "bank_code_1": "103",
                    "bank_name_1": "新光商銀",
                    "bank_code_2": "0684",
                    "bank_name_2": "新光銀竹南",
                    "account": "1021500062896",
                    "naac_client_id": "A222277777",
                    "UserNo": null
                  },
                  {
                    "OrderNum": [
                      "account_type",
                      "bank_code_1",
                      "bank_code_2",
                      "account",
                      "naac_client_id"
                    ],
                    "account_type": "I",
                    "bank_code_1": "103",
                    "bank_name_1": "",
                    "bank_code_2": "0709",
                    "bank_name_2": "",
                    "account": "1021500062896",
                    "naac_client_id": "A271648688",
                    "UserNo": null
                  },
                  {
                    "OrderNum": [
                      "account_type",
                      "bank_code_1",
                      "bank_code_2",
                      "account",
                      "naac_client_id"
                    ],
                    "account_type": "O",
                    "bank_code_1": "103",
                    "bank_name_1": "新光商銀",
                    "bank_code_2": "0709",
                    "bank_name_2": "新光銀基隆",
                    "account": "1021500062896",
                    "naac_client_id": "A271648688",
                    "UserNo": null
                  }
                ],
                "account_type": null,
                "bank_code_1": null,
                "bank_name_1": null,
                "bank_code_2": null,
                "bank_name_2": null,
                "account": "1021500062896",
                "AnnuityData": null,
                "method": "C",
                "fullname": null,
                "account_bank": "新光銀基隆",
                "card_type": null,
                "eff_date": null,
                "phone_area_o": null,
                "phone_number_o": null,
                "phone_remark_o": null,
                "phone_area_h": null,
                "phone_number_h": null,
                "phone_remark_h": null,
                "account_owner_ph_o": null,
                "account_owner_ph_h": null,
                "account_owner_ph_m": null,
                "rece_date": null,
                "currency_1": null,
                "CRSData": {
                  "OrderNum": [
                    "custname",
                    "custkey",
                    "crs_address_type",
                    "national_cd",
                    "other_address",
                    "birth",
                    "birth_city",
                    "birth_national_cd",
                    "sign_date",
                    "xcrsn_tax_type"
                  ],
                  "custname": "空白",
                  "custkey": "A271648688",
                  "crs_address_type": "1",
                  "national": null,
                  "national_cd": null,
                  "other_address": null,
                  "birth": "民國 80 年 07 月 07 日",
                  "birth_city": "ff",
                  "birth_national": "馬利",
                  "birth_national_cd": "145",
                  "sign_date": "2019-05-28+08:00",
                  "xcrsn_tax_type": "1"
                }
              }
            ],
            "IsSuccess": "1",
            "Msg": "",
            "OrderTime": "2019/05/28 00:36:01",
            "TN_ORDER_NO": "0100000000005463",
            "VerifyType": "OTP動態密碼驗證",
            "total_prem": "33,333",
            "pol_contract_typ": "P",
            "pol_contract_typ_name": "紙本保單",
            "main_policy": "9006353133",
            "modx": "12",
            "modx_name": "年繳",
            "init_method": "C",
            "init_method_name": "信用卡",
            "PERIOD_NO": "",
            "client_name": "空白",
            "client_id": "A271648688",
            "client_rate_sex": "2",
            "client_rate_sex_name": "女",
            "client_birth": "1991/07/07 00:00:00",
            "client_birth_name": "民國80年07月07日，投保年齡為28歲",
            "benf_name": "反倒是",
            "relation_ben_death": "6",
            "relation_ben_death_name": "祖孫",
            "phoneH": null,
            "phoneO": "02-8825252(52)",
            "MobilePhone": "0952184733",
            "address_M": "台東縣臺東市臺東路1號1樓",
            "address_1": "花蓮縣富里鄉富里路1號",
            "address_notice": null,
            "client_marriage": "1",
            "client_marriage_name": "未婚",
            "insured_income": "500",
            "insured_fam_income": "800",
            "client_visit_time_ind": "100",
            "visit_time1": true,
            "visit_time2": false,
            "visit_time3": false,
            "client_rate_age": "28",
            "face_amt": 0,
            "occupation_class": "3",
            "occupation_class_code_name": "教練",
            "occupation_class_name": "第三類",
            "occupation_desc": "養殖、石化及放牧相關",
            "insured_peer_pla": null,
            "insured_peer_plan_1": null,
            "BenfList": [
              {
                "benf_name": "反倒是",
                "relation_ben_death": "6",
                "relation_ben_death_name": "祖孫",
                "benf_id": "x111111111",
                "benf_phone": "0952184733",
                "percent1": "100",
                "percent2": "100",
                "prior_ben": "1",
                "address": "台東縣臺東市臺東路1號1樓",
                "dob": "1988/05/05 00:00:00",
                "relation": "D",
                "nationality": "英屬安圭拉",
                "nationality_code": "006"
              },
              {
                "benf_name": "史蒂夫",
                "relation_ben_death": "3",
                "relation_ben_death_name": "父母子女",
                "benf_id": "A222277777",
                "benf_phone": "028825252",
                "percent1": "100",
                "percent2": "100",
                "prior_ben": "2",
                "address": "基隆市中正區山東高速大概1號",
                "dob": "1980/06/06 00:00:00",
                "relation": "D",
                "nationality": "紐威島",
                "nationality_code": "170"
              }
            ],
            "client_height": null,
            "client_weight": null,
            "WEB_PAY_SOURCE": null,
            "BankTransferAgreementFile": "/?PolicyNo=9006353133&OrderNo=0100000000005463&DocType=1",
            "EMPLOYEE_NO": null,
            "EMPLOYEE_NAME": null,
            "QuestionAnswers": null,
            "method": null,
            "method_name": "",
            "nfo_name": "否",
            "fback_cash_opt": null,
            "fback_cash_opt_name": null,
            "fback_cash_opt_1": null,
            "fback_cash_opt_1_name": null,
            "IsDisplayPDFBtn": false,
            "Bank_name": null,
            "PreferredAccount": null,
            "RenewedPrefer": "C",
            "RenewalPolicy": false,
            "revenue": 0,
            "price": 0
          },
          "IsSuccess": true,
          "Code": null,
          "Message": null,
          "Exceptions": null
        }
      }
`)

export {
  data
}
