let data = JSON.parse(`{
    "ResultCode": "0000",
    "Status": "OK",
    "Data": {
        "Result": {
            "VerifyTypeList": {
                "3": "使用簡訊 OTP 動態密碼驗證，您的手機號碼為：0912345678"
            },
            "ID": null,
            "last_update_time": null,
            "step_status": null,
            "InsAddressCity": "台東縣",
            "InsAddressDistrict": "臺東市",
            "InsAddressRoad": "臺東路1號1樓",
            "InsAddressZip": "950",
            "InsAddress": "台東縣臺東市臺東路1號1樓",
            "IsSuccess": true,
            "IsClose": false,
            "Msg": "",
            "ins_type": 6,
            "ins_type_name": "新光人壽 Up Cash 利率變動型年金保險【乙型】",
            "po_issue_date": null,
            "po_issue_date_Name": "",
            "matured_date": null,
            "matured_date_Name": "-1910年01月01日",
            "client_rate_sex": "2",
            "client_birth": "1990/01/01 00:00:00",
            "Birthday_Full": "民國 79 年 01 月 01 日",
            "coverage_cnt": 1,
            "init_method": "",
            "init_methodCht": "活期性帳戶(電子化授權/全國繳費網)",
            "face_amt": 600,
            "face_amt_max": 10000000,
            "mode_prem": 654312,
            "Accept_ind": "",
            "plan_code": "UCA99",
            "version": "1",
            "client_occupation_class": "",
            "client_occupation_class_name": "",
            "client_occupation_class_detail": "",
            "client_occupation_class_code": null,
            "client_occupation_class_code_name": null,
            "client_id": "A222277777",
            "Nationality": "219",
            "client_names": "測試女",
            "web_appl_ind": "",
            "Blacklist_ind": "",
            "benf_num": null,
            "relation_ben_death": "",
            "benf_name": "",
            "benf_dob": null,
            "benf_id": "",
            "benf_phone": "",
            "BenfAddZip": "",
            "BenfAdd_City": "",
            "BenfAdd_County": "",
            "BenfAddRemain": "",
            "BenfAddress": "",
            "relation_ben_death_seq": null,
            "relation_ben_death_seq_percent": null,
            "BenfNationalityCode": null,
            "BenfNationality": null,
            "BenfBankCode1": null,
            "BenfBankBranch1": null,
            "BenfBankName1": null,
            "BenfBankBranchName1": null,
            "BenfBankAccount1": null,
            "relation_ben_death2": "",
            "benf_name2": "",
            "benf_dob2": null,
            "benf_id2": "",
            "benf_phone2": "",
            "BenfAddZip2": "",
            "BenfAdd_City2": "",
            "BenfAdd_County2": "",
            "BenfAddRemain2": "",
            "BenfAddress2": "",
            "relation_ben_death_seq2": null,
            "relation_ben_death_seq_percent2": null,
            "BenfNationalityCode2": null,
            "BenfNationality2": null,
            "BenfBankCode2": null,
            "BenfBankBranch2": null,
            "BenfBankName2": null,
            "BenfBankBranchName2": null,
            "BenfBankAccount2": null,
            "relation_ben_death3": "",
            "benf_name3": "",
            "benf_dob3": null,
            "benf_id3": "",
            "benf_phone3": "",
            "BenfAddZip3": "",
            "BenfAdd_City3": "",
            "BenfAdd_County3": "",
            "BenfAddRemain3": "",
            "BenfAddress3": "",
            "relation_ben_death_seq3": null,
            "relation_ben_death_seq_percent3": null,
            "BenfNationalityCode3": null,
            "BenfNationality3": null,
            "BenfBankCode3": null,
            "BenfBankBranch3": null,
            "BenfBankName3": null,
            "BenfBankBranchName3": null,
            "BenfBankAccount3": null,
            "adph_type": "3",
            "phone": "0912345678",
            "dicPhone": {
                "1": "02-8825252(52)",
                "3": "0912345678"
            },
            "phone_area": "02",
            "phone_main": "8825252",
            "phone_ext": "52",
            "phone_mobile": "0912345678",
            "address1Type": "0",
            "Agreement": null,
            "AgreementString": "新光人壽Up Cash利率變動型年金保險【乙型】商品說明(6),新光人壽Up Cash利率變動型年金保險【乙型】保險單條款(8),人壽保險投保人須知_網路投保(6),要保書填寫說明(2),蒐集、處理及利用個人資料告知事項(51),病歷、醫療及健康檢查等個人資料蒐集、處理及利用聲明事項(3),配合FATCA法案蒐集、處理及利用個人資料告知事項(7),保險費暨保險單借款利息自動轉帳付款委託約定條款(6),電子單據服務約定事項(2),信用卡授權書審閱條款(7)",
            "email": "skek1008@skl.com.tw",
            "zip1": "950",
            "address1": "台東縣臺東市臺東路1號1樓",
            "city1": "台東縣",
            "district1": "臺東市",
            "road1": "臺東路1號1樓",
            "IsSaveCommu": false,
            "address2Type": "0",
            "zip2": "983",
            "address2": "花蓮縣富里鄉富里路1號",
            "city2": "花蓮縣",
            "district2": "富里鄉",
            "road2": "富里路1號",
            "IsSaveRegistered": false,
            "owner_marriage": "1",
            "owner_marriage_name": "未婚",
            "insured_height": null,
            "insured_weight": null,
            "insured_income": "",
            "insured_fam_income": "",
            "visit_time_ind": "",
            "visit_time1": "",
            "visit_time2": "",
            "visit_time3": "",
            "pol_contract_typ": "P",
            "web_order_no": "",
            "Age": "29",
            "union_process_date": "2019/04/21",
            "union_batch_no": "1",
            "IsRetry": false,
            "QusAns": null,
            "DeclarationCode": [
                "R353",
                "R333"
            ],
            "address3Type": "0",
            "zip3": "950",
            "address3": "台東縣臺東市臺東路1號1樓",
            "city3": "台東縣",
            "district3": "臺東市",
            "road3": "臺東路1號1樓",
            "qpoop_25_prem": 0,
            "fst_anny_pay_age": "",
            "anny_frequence": "",
            "qpoop_19_year": "",
            "qpoop_25_modx": "",
            "modx_99_ind": "",
            "value_ind": "",
            "elec_rcpt_ind": "",
            "AccountData": [],
            "account_type": null,
            "bank_code_1": null,
            "bank_name_1": null,
            "bank_code_2": null,
            "bank_name_2": null,
            "account": null,
            "Applicant_account_type": "O",
            "Applicant_BankCode": null,
            "Applicant_BankName": null,
            "Applicant_BranchCode": null,
            "Applicant_BranchName": null,
            "Applicant_Account": null,
            "AnnuityData": [],
            "method": "B",
            "methodCht": "銀行或郵局帳戶轉帳",
            "fullname": null,
            "account_bank": null,
            "card_type": null,
            "str_date": null,
            "eff_date": null,
            "rece_date": null,
            "currency_1": "NTD",
            "fback_cash_opt": null,
            "fback_cash_opt_1": null,
            "modx": "12",
            "ProvisionReview": [],
            "insure_peer_pla": null,
            "insure_peer_plan_1": null,
            "web_collect_code": null,
            "web_equipment_code": "03",
            "original_policy_no": null,
            "accept_birthday_present": null,
            "EmployeeNo": null,
            "SalespersonName": null,
            "endterm_benf_relation": null,
            "endterm_benf_name": null,
            "endterm_benf_id": null,
            "endterm_benf_Phone": null,
            "endterm_benf_AddZip": "",
            "endterm_benf_Add_City": "",
            "endterm_benf_AddCounty": "",
            "endterm_benf_AddRemain": "",
            "endterm_benf_Address": "",
            "endterm_benf_dob": null,
            "endterm_benf_Nationality": null,
            "endterm_benf_NationalityCode": null,
            "USER_NO": null,
            "HavePreferredAccount": false,
            "Renewed_Prefer": false,
            "Payment_Prefer": false,
            "IsOneTimePayment": false,
            "OtpSendTime": null,
            "OtpValidateTime": null,
            "TrvDays": 0,
            "SupplementalTerms": null,
            "client_residency": "1",
            "Proposer": null,
            "rece_no": null,
            "AuthorizedRep": null,
            "SpouseAuthRep": null,
            "DependantAuthRep": null,
            "CRSData": {
                "OrderNum": [
                    "custname",
                    "custkey",
                    "crs_address_type",
                    "national_cd",
                    "other_address",
                    "birth",
                    "birth_city",
                    "birth_national_cd",
                    "sign_date",
                    "xcrsn_tax_type"
                ],
                "custname": null,
                "custkey": null,
                "crs_address_type": null,
                "national": null,
                "national_cd": null,
                "other_address": null,
                "birth": null,
                "birth_city": null,
                "birth_national": null,
                "birth_national_cd": null,
                "sign_date": null,
                "xcrsn_tax_type": null
            },
            "IsTaiwanTaxDuty": null,
            "OrderNo": null,
            "NoticeNo": null,
            "PayAMT": null,
            "PaymentStatus": null,
            "PolicyNo": null,
            "Year": 0,
            "Amount": 0
        },
        "IsSuccess": true,
        "Code": null,
        "Message": null,
        "Exceptions": null
    }
}`)

export {
  data
}
