export default {
  JOB: 'JOB',
  JOBDATA: 'JOBDATA',
  NATION: 'NATION',
  NATIONDATA: 'NATIONDATA',
  OCCUPATION: 'OCCUPATION',
  OCCUPATIONDATA: 'OCCUPATIONDATA',
  POSTDATA: 'POSTDATA',
  CITY: 'CITY',
  CITYDATA: 'CITYDATA'
}
