export default {
  JOB: 'JOB',
  JOBDATA: 'JOBDATA',
  NATION: 'NATION',
  NATIONDATA: 'NATIONDATA',
  OCCUPATION: 'OCCUPATION',
  OCCUPATIONDATA: 'OCCUPATIONDATA',
  POSTDATA: 'POSTDATA',
  CITY: 'CITY',
  CITYDATA: 'CITYDATA',
  DISTRICT: 'DISTRICT',
  DISTRICTDATA: 'DISTRICTDATA',
  BANK: 'BANK',
  BANKDATA: 'BANKDATA',
  BANKBRANCHESDATA: 'BANKBRANCHESDATA',
  ISINIT: 'ISINIT',
  BENEFICIARY: 'BENEFICIARY'
}
